### ISSUE TITLE
No existe Endpoint para consultar los ingredientes de una cerveza

### ISSUE THREAD

**Issue by jennifert04** [jdrodas/CervezasColombia#1]
Se requiere saber para una cerveza especificada cuáles son sus ingredientes y de qué tipo son

**Comment by jdrodas** [comment]
Hola @jennifert04 , gracias por registrar un issue!

Por favor tener presente que la explicación a continuación corresponde a la implementación inicial del requerimiento, pero en el código podrás encontrar versiones posteriores que pueden resultar de validaciones o requerimientos adicionales.

Efectivamente no teníamos EndPoint para atender esta necesidad. Lo hicimos de esta forma.

**1. Registrar nuevo Service/Repository en Program.cs:**

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/d36e254d-20b3-44ce-89ef-48a73d9dcfa7)

**2. Crear Controller, Service, Repository y Model para la entidad Cerveza:**

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/efea22f4-c380-43bf-9419-bdb744faaf4b)

**3. Crear un modelo para el Ingrediente:**

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/e5872bdd-ba1f-4a08-8c3e-0496a13c68ee)

**4. Crear en el Controller una ruta específica para los ingredientes por Cerveza y vincularlo a los demás elementos en el servicio y repositorio:**

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/e8c9fcd8-9307-45df-88f5-bc2ef65f94a9)

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/c4644ed9-3c01-4da4-ae11-c6f05f69e51b)


Finalmente, probando el nuevo EndPoint, encontramos esto específico para los ingredientes de Cervezas:

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/3e36ba0f-2c4d-4955-8be3-eea4a37c8232)
