### ISSUE TITLE
No existe endpoint para actualizar la información de las cervecerías en Cervecerías

### ISSUE THREAD

**Issue by Jvalencia25** [jdrodas/CervezasColombia#10]
Se desea poder editar la información de las cervecerías, en caso de que una cervecería decida hacer un rebranding, se busca que la base de datos esté actualizada en cuanto al nombre, sitio web e instagram, o incluso ubicación para que la BD no tenga información obsoleta

**Comment by jdrodas** [comment]
Hola @Jvalencia25 , muchas gracias por tu aporte

Hemos revisado el detalle del funcionamiento de la ruta de actualización para la cervecería en el respectivo controller.

<img width="386" alt="image" src="https://github.com/jdrodas/CervezasColombia/assets/29258977/d38d163c-941c-4c24-a922-ee9bf7194f7f">

Se implementaron las siguientes validaciones en la capa de servicio:

- Que el nuevo nombre tenga longitud superior a cero y que no exista previamente en otro registro
- Que el nuevo sitio web tenga longitud superior a cero y que no exista previamente en otro registro
- Que el nuevo instagram tenga longitud superior a cero y que no exista previamente en otro registro
- Que la nueva ubicación exista previamente registrada.

Actualización del código:
-Se actualizó el servicio para que obtenga el valor del objeto resultante luego de realizar la operación.
-Se actualizó el controller para que visualice la cervecería actualizada. Se implementó para las rutas que devuelven este objeto.
-Se actualizó el repository para incluir el valor del atributo **ubicacion_id** y de esa forma permitir la comparación al momento de actualizar con valores idénticos. La clase **Cerveceria**
-Se actualizó la nomenclatura del parametro **id** a **cerveceria_id** para evitar confusiones en la implementación de las sentencias SQL. Se implementó para todas las rutas del EndPoint
