### ISSUE TITLE
No se tiene procedimiento asociado a "Insertar Envasado"

### ISSUE THREAD

**Issue by Daniel207eae1** [jdrodas/CervezasColombia#15]
No hay un procedimiento asociado a la inserción de envasado.

**Comment by jdrodas** [comment]
Gracias @Daniel207eae1 !

Se ha creado el procedimiento p_inserta_envasado:

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/3e584e87-99fa-47ec-ab21-64bdca60eea9)


Se actualiza el repositorio EnvasadoRepository

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/451fa422-bab7-46fe-88f8-9912f8eea6cc)
