### ISSUE TITLE
No hay un procedimiento asociado a "Actualización de envasado"

### ISSUE THREAD

**Issue by Daniel207eae1** [jdrodas/CervezasColombia#16]
No existe un procedimiento asociado a la actualización de envasado.

**Comment by jdrodas** [comment]
Gracias @Daniel207eae1 

Se creo procedimiento p_actualiza_envasado:

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/2f0aabba-9658-425c-bbd0-e598c42324af)

Se actualizó repositorio EnvasadoRepository:

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/308f9ae2-8ff3-4059-8ea0-fe888d9165d7)
