### ISSUE TITLE
No hay un procedimiento asociado a "Eliminación envasado"

### ISSUE THREAD

**Issue by Daniel207eae1** [jdrodas/CervezasColombia#17]
No existe un procedimiento para eliminar un envasado.

**Comment by jdrodas** [comment]
Gracias @Daniel207eae1 

Se creó el procedimiento p_elimina_envasado:

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/206cb331-a8ac-4e72-9be5-71bf16ca5949)

Se actualizó el repositorio EnvasadoRepository:

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/3ad422e7-d9ec-43fe-baa3-19b3b82ef476)

**Comment by jdrodas** [comment]
Este mejora ya se encuentra aplicada en el código del repositorio
