### ISSUE TITLE
No hay un procedimiento asociado a "Actualización de ingredientes".

### ISSUE THREAD

**Issue by ElianaGiraldo-98** [jdrodas/CervezasColombia#18]

**Comment by jdrodas** [comment]
Este incidente se cerró erroneamente con el commit de los envasados. Se abre para que quede registrada la evidencia de su solución.

**Comment by jdrodas** [comment]
Gracias @ElianaGiraldo-98 

Se ha actualizado solamente el repositorio IngredienteRepositorio, mientras que se crearon los procedimientos asociados a la creación, actualización y borrado de ingredientes

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/36a68f28-3a25-49e3-9f70-09d189284cd2)

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/56b7971b-161f-4b1b-851d-cf57ef73e51f)

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/46b2a14b-d5bf-4c39-800e-eb4d3feac1bc)

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/75f37426-2450-4bdf-ab92-620ab2d216f2)
