### ISSUE TITLE
Conflicto de tipo de dato para el atributo volumen en el modelo para envasado_cerveza

### ISSUE THREAD

**Issue by Joseale58** [jdrodas/CervezasColombia#20]
En la BBDD el campo está float, en la clase int... conflicto de tipos

**Comment by jdrodas** [comment]
Gracias @Joseale58 !

Estas son las evidencias que soportan el hallazgo.

Al utilizar la ruta para agregar un envasado para la cerveza:

<img width="401" alt="image" src="https://github.com/jdrodas/CervezasColombia/assets/29258977/8144ceb6-b585-4ced-a97b-0b7daf09cdcd">

El error generado es: 

<img width="698" alt="image" src="https://github.com/jdrodas/CervezasColombia/assets/29258977/ef5d7d3f-6a91-40af-8607-14811a2aac1c">

No procesa un volumen con dígitos decimales.

Revisando la definición de la tabla:

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/6449a63d-249b-46cf-a1be-da42f9c0ae9c)

Pero al revisar el modelo:

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/11a492d0-c1d2-4955-b1cc-ed328a1bd26e)

Se identifica la falla en el modelo. Se procede a corregir la definición.
