### ISSUE TITLE
No se encuentra una columna para las cordenadas de las cervecerias

### ISSUE THREAD

**Issue by RollingCC121** [jdrodas/CervezasColombia#21]
En la tabla ubicacion no se encuentra una columna para asociar las cordenadas de las cervecerias

**Comment by jdrodas** [comment]
Gracias @RollingCC121!

Para implementar este requerimiento de manera consistente en los diferentes motores garantizando la mínima cantidad de cambios, se almacenarán los componentes de la coordenada geográfica como valores reales independientes, es decir dos columnas adicionales en lugar de una.

Validamos que PostgreSQL tiene el tipo de dato Point y en MongoDB podremos usar geoJSON para almacenar estos datos. Sin embargo, dejaremos que la API se encargue de lidiar con la validación y manipulación de estos datos.

Se modificaron ambos proyectos  de API (SQLite y PostgreSQL) y se realizaron las correspondientes modificaciones en modelo, repositorio y servicio. En el caso de PostgreSQL, se modificaron los procedimientos para creación y actualización de ubicaciones para que recibieran sus respectivos nuevos parámetros.

<img width="477" alt="image" src="https://github.com/jdrodas/CervezasColombia/assets/29258977/3ce00db3-7865-4caa-8104-f9de9b12a2c8">

<img width="581" alt="image" src="https://github.com/jdrodas/CervezasColombia/assets/29258977/77f09c82-9d13-475e-b63f-ee7dd66bd326">

<img width="434" alt="image" src="https://github.com/jdrodas/CervezasColombia/assets/29258977/3be43194-68c4-4e6b-9c03-59daeaef3a3e">

Finalmente, a los archivos de carga, le colocamos a cada ubicación sus respectivas coordenadas geográficas! ;-)
