### ISSUE TITLE
Agregar atributos para mejorar la generación de JSON

### ISSUE THREAD

**Issue by JJ-OO** [jdrodas/CervezasColombia#24]
Solo como sugerencia, se podria añadir al modelo en PosgreSQL especificaciones de property name y representation en cada elemento para que el archivo Json salga mas organizadito 👉👈 (Como se hizo con Ubicacion en mongo)

**Comment by jdrodas** [comment]
Gracias @JJ-OO !

Esta mejora se la hemos colocado tanto al proyecto en SQL como al de PostgreSQL.

Para demostrarlo, aqui un fragmento de código para Estilo:

<img width="440" alt="image" src="https://github.com/jdrodas/CervezasColombia/assets/29258977/6f7a2737-9136-4384-80e4-47e4e53de964">
