### ISSUE TITLE
No hay control de excepciones  cuando se devuelve un objeto nulo en el UbicacionesRepository

### ISSUE THREAD

**Issue by jero0137** [jdrodas/CervezasColombia#26]
No hay control de excepciones para el metodo GetById

**Comment by jdrodas** [comment]
Gracias @jero0137,

La estrategia más simple consiste en colocar un condicional que valide si el objeto resultante es nulo:

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/128fccce-dcd2-42bf-bb43-4492e2347b47)

De esta manera, el servicio controla la excepción validando si llega el objeto predeterminado..

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/a8ac4d8e-1a7a-4d07-afef-d877a9638898)

Y el controlador lo maneja más fácilmente:

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/d8703f34-2acc-4d02-9f0f-150abc48d27f)
