### ISSUE TITLE
Información omisa en colección de cervezas

### ISSUE THREAD

**Issue by Joseale58** [jdrodas/CervezasColombia#28]
En las CervezasEnvasados cuando se traen la colección de cervezas, las mismas, no traen el envasado ni la unidad de volumen.

También de anotar, en buenas prácticas, el de no declarar vars dentro de un ciclo

**Comment by jdrodas** [comment]
Gracias @Joseale58 

Estas son las evidencias de lo encontrado en este issue:

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/6922ea81-730d-4f00-8492-d9d2bf9643c1)

Cuando se visualiza las cervezas por Envasado, se visualiza la cerveza, pero no la información del envasado, es decir, que unidad de volumen y la cantidad de volumen asociada a este envasado.

Por otro lado, en el EnvasadoRepository, en el método GetAssociatedBeersAsync, se evidencia esta forma para obtener las cervezas asociadas al envasado:

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/2db8da58-7a7f-4af3-9c33-e2aca73f2397)

**Comment by jdrodas** [comment]
Gracias @Joseale58,

Esta es la solución a este incidente.

El resultado esperado es este:

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/44274d0f-ab98-4d66-8fd6-a5b78dd65ca6)

La respuesta de la ruta ahora incluye la información del envasado de la cerveza.

Se creó una nueva clase que se llama CervezaEnvasada que es utilizada para dar la respuesta a la petición.

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/12e894e6-4067-483d-b811-8946266c3b09)

En el repositorio de la cervezas, se realizó el cambio asi:

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/badcdc2c-6286-4c80-9dfb-45d2db67db4f)

Y en el EnvasadoService se realiza el mapeo de una cerveza con las propiedades adicionales para la cerveza envasada:

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/6eaa2dd4-ec2c-4c32-8856-f0d1b07b82e9)
