### ISSUE TITLE
Error al registrar un nuevo envase para una cerveza

### ISSUE THREAD

**Issue by alejolondonm** [jdrodas/CervezasColombia#30]
Validar que el ID de la cerveza informado en el URL del Endpoint coincida con la cervecería y la cerveza en el body.

**Comment by jdrodas** [comment]
Gracias @alejolondonm !

Se identificó que este error estaba en las rutas de inserción y borrado de envasados para las cervezas. Se colocó una validación que consiste en buscar primero la cerveza por nombre y cervecería y luego comparar el id de la cerveza resultante con el ID proporcionado en el URL.

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/3a0333f2-92bb-4e15-996e-c024f8afc043)
