### ISSUE TITLE
Implementar paginación en el Endpoint de Cervezas

### ISSUE THREAD

**Issue by JulianG91012** [jdrodas/CervezasColombia#31]
Se requiere implementar paginación para el endpoint de cervezas para que no se muestren todas las cervezas en una sola página.

**Comment by jdrodas** [comment]
Hola!

Se implementó la funcionalidad de paginación para el endpoint de las cervezas, según lo implementado previamente en otros endpoints:

<img width="713" alt="image" src="https://github.com/jdrodas/CervezasColombia/assets/29258977/7f9125d3-c489-45af-94a9-7e45e67cf4c0">

Se verifica funcionamiento y se da por cumplido el requerimiento.
