### ISSUE TITLE
Obtener cervecería por multiples propiedades

### ISSUE THREAD

**Issue by Joseale58** [jdrodas/CervezasColombia#33]
Se requiere poder obtener una cervecería por diferentes atributos, como por e.g. el id, el nombre o instagram

**Comment by jdrodas** [comment]
Gracias @Joseale58!

Los cambios realizados afectaron los siguientes archivos:

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/468faccb-b27e-4c1e-8408-5c78d04eb159)

Lo primero, es crear una clase ConsultaCerveceria que contenga los parametros por los cuales se puede buscar la Cerveceria:

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/e55a98d1-0bf0-4cf9-a4bf-151d196549e0)

Luego, consolidamos en un solo método, las rutas asociadas a la obtención de la cerveceria, especificando los parámetros de consulta:

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/c0061fb9-bdbd-43a2-9ad7-9d717c1b0503)

Al interior del método, seleccionamos la combinación de valores que mejor se ajuste a las necesidades de consulta:

- Si todos los parametros son nulos, se trae todas las cervecerias.
- Si el Id no es nulo, se trae la cerveceria detallada asociada
- Si el nombre no es nulo, se trae la cerveceria detallada asociada
- Si el instagram no es nulo, se trae la cerveceria detallada asociada

Las respuestas quedan asi:

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/5335012c-5539-4f76-abaf-1b26497e38af)

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/de49362d-c2dc-49d1-825a-457437e3a814)

![image](https://github.com/jdrodas/CervezasColombia/assets/29258977/52d55a66-b1c1-4dcc-9f12-b033db54c340)
