### ISSUE TITLE
No existe ruta en el endPoint de Ubicacion para actualizar a una ubicacion existente

### ISSUE THREAD

**Issue by RollingCC121** [jdrodas/CervezasColombia#4]
En el controller de ubicaciones, no existe ruta para actualizar la ubicación existente.

Se debe verificar:
- Que la combinación municipio, departamento sea única.
- Si la combinación ya existe, indicar que no se debe actualizar.

**Comment by jdrodas** [comment]
Gracias @RollingCC121 !

Se habilitó la ruta para actualizar ubicación existente en el controlador asociado a las Ubicaciones.

Se afectaron Controller, Servicio, Repositorio y Modelo:

<img width="307" alt="image" src="https://github.com/jdrodas/CervezasColombia/assets/29258977/442ed4ac-5636-4674-92b0-9bcc83b74ca9">

Con esta acción se hace refactorización de las rutas existentes y se agrega rutas faltantes para la creación y borrado de ubicaciones.
