### ISSUE TITLE
No existe ruta para borrar ingredientes

### ISSUE THREAD

**Issue by ElverTunubala** [jdrodas/CervezasColombia#5]
En el controlador de Ingredientes (que no existe todavía) se debe tener una ruta para eliminar un ingrediente existente.

Validaciones:
- Que no esté siendo utilizado en las cervezas

**Comment by jdrodas** [comment]
Gracias @ElverTunubala !

Se agregó Controlador, Servicio, Repositorio y se modificó el modelo.

Específicamente para los ingredientes, la validación quedó de esta forma en el servicio:

<img width="1043" alt="image" src="https://github.com/jdrodas/CervezasColombia/assets/29258977/5f78e46f-cbad-4a80-80d4-481509ba7d8e">


Se procedió a completar el resto de las rutas faltantes: GetAll, GetById, Create, Update.
