### ISSUE TITLE
No existe ruta en el Endpoint de Envasados para crear un envasado

### ISSUE THREAD

**Issue by Daniel207eae1** [jdrodas/CervezasColombia#6]
En el EndPoint de Envasados, no existe una ruta que permita crear un nuevo envasado.

Validaciones:

- Que el nombre nuevo no exista previamente

**Comment by jdrodas** [comment]
Gracias @Daniel207eae1 !

Se realizó modificación en el controlador, servicio, repositorio y modelo.

Específicamente para la creación se implementaron las siguientes validaciones en el servicio:

<img width="887" alt="image" src="https://github.com/jdrodas/CervezasColombia/assets/29258977/46a2f53b-bd7c-4cdc-a338-d631d1d0570d">
