### ISSUE TITLE
No existe ruta para Actualizar Envasado

### ISSUE THREAD

**Issue by JulianG91012** [jdrodas/CervezasColombia#7]
En el controlador de Envasados se debe tener una ruta para actualizar un envasado existente.

## **Validaciones:**
- Que exista el envasado
- Que el valor modificado esté dentro de un rango posible (Ej. No números negativos)
- Que hayan modificaciones

**Comment by jdrodas** [comment]
Gracias @JulianG91012 !

Se realizó modificación en el controlador, servicio, repositorio y modelo.

Específicamente para la actualización se implementaron las siguientes validaciones en el servicio:

<img width="1092" alt="image" src="https://github.com/jdrodas/CervezasColombia/assets/29258977/174e9f94-f766-4a89-b6bc-ff78e9ca7532">

Se modificó la clase Envasado para hacerla más simplificada para esta necesidad. Se creó adicionalmente la clase EnvasadoCerveza para utilizarla en el caso específico de las cervezas que utilizan ese envasado particular.
