### ISSUE TITLE
No existe ruta para eliminar una cerveza en Cerveza

### ISSUE THREAD

**Issue by JJ-OO** [jdrodas/CervezasColombia#8]
Que el controlador de Cerveza permita eliminar una cerveza. 

Verificar:
- Que exista la cerveza
- Integridad referencial, afectacion de registros relacionados

**Comment by jdrodas** [comment]
Gracias @JJ-OO 

Se ha agregado la ruta para eliminar una cerveza en el Controlador respectivo.

Se modificó Controlador, Servicio y Repositorio

<img width="359" alt="image" src="https://github.com/jdrodas/CervezasColombia/assets/29258977/e2b8dc49-741a-4373-8db1-e5e8f20203b3">

En este momento se valida si tiene ingredientes y envasados previamente asignados y limita la acción hasta que éstos estén previamente eliminados. Posteriormente se puede elegir que al eliminar la cerveza, también se eliminen registros de envasados_cervezas y de ingredientes_cervezas.
